export const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000";

export const FEATURES_META = {
  VEHTYPE: {
    label: "Vehicle Type",
    type: "select",
    options: ["Automobile", "Motorcycle", "Bicycle", "Truck", "Bus", "Pedestrian", "Other"],
  },
  INITDIR: {
    label: "Initial Direction",
    type: "direction",
    options: ["N", "S", "E", "W"],
  },
  AUTOMOBILE: {
    label: "Automobile Involved",
    type: "toggle",
  },
  ACCLOC: {
    label: "Accident Location",
    type: "select",
    options: [
      "At Intersection",
      "Non Intersection",
      "Intersection Related",
      "Private Driveway",
      "At/Near Private Drive",
      "Overpass or Bridge",
      "Trail",
      "Other",
    ],
  },
  HOOD_140: {
    label: "Neighbourhood (1–140)",
    type: "number",
    min: 1,
    max: 140,
  },
  ROAD_CLASS: {
    label: "Road Class",
    type: "select",
    options: [
      "Major Arterial",
      "Minor Arterial",
      "Collector",
      "Local",
      "Expressway",
      "Expressway Ramp",
      "Laneway",
      "Other",
    ],
  },
  IMPACTYPE: {
    label: "Impact Type",
    type: "select",
    options: [
      "Rear End",
      "Angle",
      "Sideswipe",
      "Head On",
      "Turning Movement",
      "SMV Other",
      "Cyclist Collisions",
      "Pedestrian Collisions",
      "Other",
    ],
  },
  DISTRICT: {
    label: "District",
    type: "select",
    options: ["Toronto and East York", "North York", "Scarborough", "Etobicoke York"],
  },
  INVTYPE: {
    label: "Involvement Type",
    type: "select",
    options: [
      "Driver",
      "Passenger",
      "Pedestrian",
      "Cyclist",
      "Motorcycle Driver",
      "Moped Driver",
      "Other",
    ],
  },
  RDSFCOND: {
    label: "Road Surface Condition",
    type: "select",
    options: ["Dry", "Wet", "Loose Snow", "Packed Snow", "Ice", "Slush", "Loose Sand/Gravel", "Other"],
  },
  INVAGE: {
    label: "Involved Person Age",
    type: "number",
    min: 0,
    max: 100,
  },
  VISIBILITY: {
    label: "Visibility",
    type: "select",
    options: ["Clear", "Rain", "Snow", "Fog", "Freezing Rain", "Strong Wind", "Drifting Snow", "Other"],
  },
  DIVISION: {
    label: "Police Division",
    type: "select",
    options: ["D11", "D12", "D13", "D14", "D22", "D23", "D31", "D32", "D33", "D41", "D42", "D43", "D51", "D52", "D53", "D54", "D55"],
  },
  LIGHT: {
    label: "Light Condition",
    type: "select",
    options: [
      "Daylight",
      "Dark",
      "Dusk",
      "Dawn",
      "Dark, artificial",
      "Dusk, artificial",
      "Dawn, artificial",
      "Daylight, artificial",
      "Other",
    ],
  },
  TRAFFCTL: {
    label: "Traffic Control",
    type: "select",
    options: [
      "No Control",
      "Traffic Signal",
      "Stop Sign",
      "Yield Sign",
      "School Guard",
      "Police Control",
      "Traffic Controller",
      "Pedestrian Crossover",
      "Other",
    ],
  },
  YEAR: { label: "Year", type: "number", min: 2006, max: new Date().getFullYear() },
  MONTH: {
    label: "Month",
    type: "month",
    options: ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],
  },
  HOUR: { label: "Hour of Day", type: "hour" },
  DAY_OF_WEEK: {
    label: "Day of Week",
    type: "weekday",
    options: ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],
  },
  SPEEDING: { label: "Speeding", type: "toggle" },
  ALCOHOL: { label: "Alcohol Involved", type: "toggle" },
  AG_DRIV: { label: "Aggressive Driving", type: "toggle" },
};

export const STEPS = [
  {
    id: "time",
    title: "When",
    subtitle: "Date & time of the incident",
    icon: "Clock",
    fields: ["YEAR", "MONTH", "DAY_OF_WEEK", "HOUR"],
  },
  {
    id: "location",
    title: "Where",
    subtitle: "Location & district details",
    icon: "MapPin",
    fields: ["DISTRICT", "DIVISION", "HOOD_140", "ACCLOC"],
  },
  {
    id: "road",
    title: "Road",
    subtitle: "Road and environment conditions",
    icon: "Road",
    fields: ["ROAD_CLASS", "RDSFCOND", "TRAFFCTL", "VISIBILITY", "LIGHT"],
  },
  {
    id: "vehicle",
    title: "Vehicle",
    subtitle: "Vehicle and involvement info",
    icon: "Car",
    fields: ["VEHTYPE", "INITDIR", "AUTOMOBILE", "IMPACTYPE", "INVTYPE", "INVAGE"],
  },
  {
    id: "risk",
    title: "Risk Factors",
    subtitle: "Behavioural risk indicators",
    icon: "AlertTriangle",
    fields: ["SPEEDING", "ALCOHOL", "AG_DRIV"],
  },
];

export const DEFAULT_VALUES = {
  VEHTYPE: "Automobile",
  INITDIR: "N",
  AUTOMOBILE: 1,
  ACCLOC: "At Intersection",
  HOOD_140: 70,
  ROAD_CLASS: "Major Arterial",
  IMPACTYPE: "Angle",
  DISTRICT: "Toronto and East York",
  INVTYPE: "Driver",
  RDSFCOND: "Dry",
  INVAGE: 35,
  VISIBILITY: "Clear",
  DIVISION: "D51",
  LIGHT: "Daylight",
  TRAFFCTL: "Traffic Signal",
  YEAR: new Date().getFullYear(),
  MONTH: 6,
  HOUR: 14,
  DAY_OF_WEEK: 4,
  SPEEDING: 0,
  ALCOHOL: 0,
  AG_DRIV: 0,
};
